(() => {
const $=(s,r=document)=>r.querySelector(s), slug=document.body.dataset.tool||location.pathname.split('/').pop().replace('.html','');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const words=s=>(s.match(/[A-Za-z][A-Za-z0-9+#.-]*/g)||[]);
const stop=new Set('the and for with from that this your you are our their have has was were will can may into about through using use used a an to of in on at by or as is it be we i me my they he she his her its but not do does did than then also all any more most some such each'.split(' ')); const uniq=a=>[...new Set(a.map(x=>x.toLowerCase()).filter(x=>x&&!stop.has(x)))];
const fmt=n=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:2}):'—';
const money=n=>Number.isFinite(n)?'$'+n.toLocaleString(undefined,{maximumFractionDigits:2}):'—';
const resultBox=$('#result'); function setResult(h){resultBox.innerHTML=h;resultBox.scrollIntoView({behavior:'smooth',block:'nearest'});}
function f(label,id,ph,type='text',value=''){return '<label>'+esc(label)+'<input id="'+id+'" type="'+type+'" placeholder="'+esc(ph)+'" value="'+esc(value)+'"></label>'}
function a(label,id,ph){return '<label>'+esc(label)+'<textarea id="'+id+'" rows="10" placeholder="'+esc(ph)+'"></textarea></label>'}
const D={
'resume-score':['RESUME','Resume Score','Get a practical 100-point resume review using measurable, browser-side checks.',a('Paste your resume','resume','Paste your resume text here...'),'Score my resume'],
'ats-resume-checker':['RESUME','ATS Resume Checker','Check common ATS-friendly signals: contact details, headings, keywords, formatting, length and readability.',a('Resume text','resume','Paste the full resume text here...'),'Check ATS readiness'],
'resume-keyword-checker':['RESUME','Resume Keyword Checker','Compare your resume with a target job description and surface missing terms worth reviewing.',a('Resume','resume','Paste your resume...')+a('Job description','job','Paste the target job description...'),'Find keyword gaps'],
'resume-summary-generator':['RESUME','Resume Summary Generator','Turn your experience into concise, professional summary options without sending your text anywhere.',a('Your experience','resume','Role, years of experience, skills, industries, achievements...'),'Generate summaries'],
'resume-bullet-generator':['RESUME','Resume Bullet Generator','Convert a responsibility or accomplishment into stronger action-and-result resume bullets.',a('Your raw experience','text','Example: Managed customer support team and improved response time...'),'Generate bullets'],
'resume-length-checker':['RESUME','Resume Length Checker','Check word count, section balance and a simple length recommendation.',a('Resume text','resume','Paste your resume...'),'Check length'],
'resume-formatter':['RESUME','Resume Formatter','Normalize common resume text patterns and produce a cleaner copy you can paste into a document.',a('Resume text','resume','Paste your resume text...'),'Format text'],
'cover-letter-generator':['COVER LETTER','Cover Letter Generator','Create a structured first draft from your role, company and experience details.',f('Target role','role','e.g. Product Manager')+f('Company','company','e.g. Acme')+a('Your experience','experience','Key achievements, skills and relevant background...'),'Generate draft'],
'cover-letter-checker':['COVER LETTER','Cover Letter Checker','Review clarity, length, personalization and evidence in a cover letter.',a('Cover letter','letter','Paste your cover letter...'),'Check letter'],
'job-description-analyzer':['JOB SEARCH','Job Description Analyzer','Extract likely skills, requirements, keywords and signals from a job description.',a('Job description','job','Paste the full job description...'),'Analyze job'],
'resume-vs-job-matcher':['JOB SEARCH','Resume vs Job Matcher','Estimate keyword coverage between a resume and a target job description using transparent browser-side matching.',a('Resume','resume','Paste resume...')+a('Job description','job','Paste job description...'),'Match resume'],
'job-application-tracker':['JOB SEARCH','Job Application Tracker','Keep a lightweight application tracker in your browser. Data stays on this device.',f('Company','company','Company name')+f('Role','role','Job title')+f('Stage','stage','Applied / Screen / Interview / Offer')+f('Follow-up date','date','','date')+f('Notes','notes','Short note'),'Save application'],
'salary-to-hourly-calculator':['SALARY','Salary to Hourly Calculator','Convert annual salary into an estimated hourly rate using your work schedule.',f('Annual salary','salary','e.g. 75000','number')+f('Hours per week','hours','40','number','40')+f('Weeks per year','weeks','52','number','52'),'Calculate hourly rate'],
'hourly-to-salary-calculator':['SALARY','Hourly to Salary Calculator','Convert an hourly wage into estimated weekly, monthly and annual pay.',f('Hourly rate','rate','e.g. 35','number')+f('Hours per week','hours','40','number','40')+f('Weeks per year','weeks','52','number','52'),'Calculate salary'],
'raise-calculator':['SALARY','Raise Calculator','Calculate your new salary and estimated increase from a percentage raise.',f('Current salary','salary','e.g. 70000','number')+f('Raise percentage','raise','e.g. 5','number'),'Calculate raise'],
'job-offer-comparison':['SALARY','Job Offer Comparison','Compare two offers across base pay, bonus and benefits with a transparent total-value estimate.',f('Offer A base salary','a','e.g. 80000','number')+f('Offer A bonus','ab','e.g. 5000','number','0')+f('Offer A annual benefits value','av','e.g. 3000','number','0')+f('Offer B base salary','b','e.g. 85000','number')+f('Offer B bonus','bb','e.g. 2000','number','0')+f('Offer B annual benefits value','bv','e.g. 2500','number','0'),'Compare offers'],
'interview-question-generator':['INTERVIEW','Interview Question Generator','Generate a focused practice set based on a role and interview type.',f('Target role','role','e.g. Software Engineer')+f('Interview type','type','Behavioral, technical, general'),'Generate questions'],
'star-method-builder':['INTERVIEW','STAR Method Builder','Structure a behavioral interview story into Situation, Task, Action and Result.',f('Interview question','question','Tell me about a time...')+a('Your story notes','story','What happened, what you did, and what changed...'),'Build STAR answer'],
'interview-answer-practice':['INTERVIEW','Interview Answer Practice','Review an answer for clarity, evidence, specificity and outcome focus.',a('Your interview answer','answer','Paste or write your answer...'),'Review answer'],
'interview-scorecard':['INTERVIEW','Interview Scorecard','Score your preparation across the areas that commonly matter in an interview.',f('Role','role','Target role')+f('Preparation level (1–10)','prep','7','number','7')+f('Role research (1–10)','research','7','number','7')+f('Story practice (1–10)','stories','7','number','7')+f('Questions prepared (1–10)','questions','7','number','7'),'Calculate score'],
'questions-to-ask-interviewer':['INTERVIEW','Questions to Ask Interviewer','Generate thoughtful questions based on the role and what you want to learn.',f('Target role','role','e.g. Marketing Manager')+f('Interview stage','stage','First interview, final, hiring manager...'),'Generate questions'],
'linkedin-headline-generator':['CAREER','LinkedIn Headline Generator','Create concise headline options using your role, strengths and target direction.',f('Current or target role','role','e.g. Data Analyst')+f('Top skills','skills','SQL, Python, dashboards')+f('Value or specialty','value','What you help teams achieve'),'Generate headlines'],
'professional-bio-generator':['CAREER','Professional Bio Generator','Create short professional bio options for profiles, portfolios and speaker pages.',f('Name','name','Your name')+f('Role','role','Your professional role')+a('Experience and achievements','experience','Years, industries, notable work, specialties...'),'Generate bio'],
'career-goal-planner':['CAREER','Career Goal Planner','Turn a career goal into a practical 30/60/90-day action plan.',f('Career goal','goal','e.g. Move into product management')+f('Target date','date','','date')+f('Current strength','strength','What you already have'),'Build plan'],
'skills-gap-checker':['CAREER','Skills Gap Checker','Compare your current skills with a target role and identify gaps to review.',f('Current skills','current','Excel, communication, SQL...')+f('Target role','role','e.g. Business Analyst')+f('Target skills','target','SQL, Tableau, requirements analysis...'),'Check skill gap'],
'achievement-statement-generator':['CAREER','Achievement Statement Generator','Turn work activity into measurable achievement statements.',a('What you did','work','Describe the task, challenge or responsibility...')+f('Result or metric','resultText','Time saved, revenue, growth, quality, volume...'),'Generate statements'],
'notice-period-calculator':['CAREER','Notice Period Calculator','Calculate an estimated end date from a start date and notice period.',f('Notice start date','start','', 'date')+f('Notice period (days)','days','e.g. 30','number','30'),'Calculate end date'],
'work-experience-calculator':['CAREER','Work Experience Calculator','Estimate elapsed professional experience between two dates.',f('Start date','start','', 'date')+f('End date','end','', 'date'),'Calculate experience'],
'commute-cost-calculator':['CAREER','Commute Cost Calculator','Estimate annual commuting fuel, transit and time costs.',f('One-way miles','miles','e.g. 18','number')+f('Commute days per week','days','5','number','5')+f('Fuel cost per mile','cost','e.g. 0.20','number','0.20')+f('Minutes one way','minutes','e.g. 35','number','35'),'Calculate commute'],
'remote-vs-office-calculator':['CAREER','Remote vs Office Calculator','Compare annual commuting and time costs between remote and office work.',f('Annual salary','salary','e.g. 80000','number')+f('Office days per week','days','3','number','3')+f('Commute miles per day','miles','30','number','30')+f('Cost per mile','cost','0.20','number','0.20')+f('Minutes commuting per day','minutes','60','number','60'),'Compare costs']
};
const d=D[slug]||D['resume-score']; document.title=d[1]+' — Free Career Tool | Career Tools';
const title=$('#toolTitle'),lead=$('#toolLead'),k=$('#toolKicker'),form=$('#toolForm'); if(title)title.textContent=d[1];if(lead)lead.textContent=d[2];if(k)k.textContent=d[0];if(form)form.innerHTML=d[3]+'<button id="run">'+d[4]+'</button>';
const btn=$('#run'); if(!btn||!resultBox)return; const v=id=>{const e=$('#'+id);return e?e.value.trim():''}, n=id=>parseFloat(v(id))||0; function renderTracker(arr){const rows=arr.slice(0,10).map(x=>'<li><b>'+esc(x.company||'Company')+'</b> — '+esc(x.role||'Role')+' · '+esc(x.stage||'Applied')+(x.date?' · '+esc(x.date):'')+'</li>').join('');return setResult('<strong>'+arr.length+' saved application'+(arr.length===1?'':'s')+'</strong><ul>'+rows+'</ul><button class="secondary" id="clearTracker">Clear saved applications</button>')}
const list=(t,x)=>'<strong>'+esc(t)+'</strong><ul>'+x.map(q=>'<li>'+q+'</li>').join('')+'</ul>';
if(slug==='job-application-tracker'){const saved=JSON.parse(localStorage.getItem('career-applications')||'[]');if(saved.length)renderTracker(saved)}
btn.addEventListener('click',()=>{
try{
if(slug==='salary-to-hourly-calculator'){const s=n('salary'),h=n('hours'),w=n('weeks');return setResult('<strong>'+money(s/(h*w))+'/hour</strong><p>'+money(s)+' annual salary using '+h+' hours/week and '+w+' weeks/year.</p>')}
if(slug==='hourly-to-salary-calculator'){const r=n('rate'),h=n('hours'),w=n('weeks'),y=r*h*w;return setResult('<strong>'+money(y)+'/year</strong><p>Weekly: '+money(r*h)+' · Monthly estimate: '+money(y/12)+'</p>')}
if(slug==='raise-calculator'){const s=n('salary'),p=n('raise'),y=s*(1+p/100);return setResult('<strong>'+money(y)+'</strong><p>Increase: '+money(y-s)+' · Monthly increase: '+money((y-s)/12)+'</p>')}
if(slug==='notice-period-calculator'){const d=new Date(v('start')+'T00:00:00'),days=n('days');if(isNaN(d))return setResult('<strong>Enter a valid start date.</strong>');d.setDate(d.getDate()+days);return setResult('<strong>'+d.toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})+'</strong><p>Estimated date after '+days+' days.</p>')}
if(slug==='work-experience-calculator'){const a=new Date(v('start')),b=new Date(v('end'));if(isNaN(a)||isNaN(b)||b<a)return setResult('<strong>Check your dates.</strong>');const days=Math.round((b-a)/86400000),years=Math.floor(days/365.25),months=Math.floor((days-years*365.25)/30.44);return setResult('<strong>'+years+' years '+Math.max(0,months)+' months</strong><p>Approx. '+days.toLocaleString()+' days.</p>')}
if(slug==='commute-cost-calculator'){const annualMiles=n('miles')*2*n('days')*52;return setResult('<strong>'+money(annualMiles*n('cost'))+'/year</strong><p>Approx. '+fmt(annualMiles)+' miles/year and '+fmt(n('minutes')*2*n('days')*52/60)+' commute hours/year.</p>')}
if(slug==='remote-vs-office-calculator'){const cost=n('miles')*n('days')*52*n('cost'),hours=n('minutes')*n('days')*52/60;return setResult('<strong>Office commute cost: '+money(cost)+'/year</strong><p>Approx. '+fmt(hours)+' hours/year commuting.</p>')}
if(slug==='job-offer-comparison'){const A=n('a')+n('ab')+n('av'),B=n('b')+n('bb')+n('bv');return setResult('<strong>Offer totals</strong><p>Offer A: '+money(A)+' · Offer B: '+money(B)+'</p><p>Simple annual estimate using base pay, bonus and stated benefits. Taxes, equity and non-financial factors are not included.</p>')}
if(slug==='resume-length-checker'){const x=v('resume'),w=words(x).length;return setResult('<strong>'+fmt(w)+' words</strong><p>'+(w<250?'Likely short for a detailed resume.':w>900?'Consider trimming repetitive content.':'Length is within a practical range for many resumes.')+'</p>')}
if(slug==='ats-resume-checker'||slug==='resume-score'){const x=v('resume'),w=words(x),signals=[/experience|work history/i.test(x),/education/i.test(x),/skills/i.test(x),/email|@/i.test(x),/[0-9%$]/.test(x),w.length>=250];const score=Math.min(100,45+(signals.filter(Boolean).length*9)+Math.min(10,w.length/50));return setResult('<strong>'+Math.round(score)+'/100</strong><ul>'+signals.map((q,i)=>'<li>'+(q?'✓':'○')+' '+['Experience section','Education section','Skills section','Contact signal','Metrics detected','Sufficient text length'][i]+'</li>').join('')+'</ul>')}
if(slug==='resume-keyword-checker'||slug==='resume-vs-job-matcher'){const r=uniq(words(v('resume'))),j=uniq(words(v('job')));if(!j.length)return setResult('<strong>Add the job description.</strong>');const common=j.filter(x=>r.includes(x)),coverage=Math.round(common.length/j.length*100),missing=j.filter(x=>x.length>3&&!r.includes(x)).slice(0,18);return setResult('<strong>'+coverage+'% keyword coverage</strong><p>'+common.length+' of '+j.length+' distinct job terms appear in the resume.</p><p class="chips">'+missing.map(esc).join(' · ')+'</p>')}
if(slug==='job-description-analyzer'){const x=v('job'),w=uniq(words(x)).filter(q=>q.length>4),skills=w.filter(q=>/sql|python|java|javascript|excel|tableau|sales|marketing|design|analysis|management|communication|leadership|project|customer|cloud|aws|azure|react|data|finance|operations/i.test(q));return setResult('<strong>'+fmt(words(x).length)+' words</strong><p>Likely skills and requirements:</p><p class="chips">'+skills.slice(0,25).map(esc).join(' · ')+'</p><p>Other notable terms: '+w.slice(0,18).map(esc).join(' · ')+'</p>')}
if(slug==='resume-summary-generator'){const x=v('resume');return setResult(list('Summary options',['Results-focused professional with experience in '+esc(x.slice(0,150))+'. Known for practical execution and measurable outcomes.','Detail-oriented professional bringing experience across '+esc(x.slice(0,150))+'. Focused on solving problems and delivering reliable results.','Experienced professional with a track record of turning responsibilities into clear outcomes, with strengths in communication and execution.']))}
if(slug==='resume-bullet-generator'){const x=v('text');return setResult(list('Bullet options',['Led '+esc(x)+', improving efficiency and execution.','Improved '+esc(x)+' by streamlining processes and reducing friction.','Delivered results through '+esc(x)+', partnering with stakeholders to improve outcomes.']))}
if(slug==='resume-formatter'){const x=v('resume').replace(/[ \\t]+/g,' ').replace(/\\n{3,}/g,'\\n\\n').replace(/^\\s+|\\s+$/gm,'');return setResult('<strong>Cleaned copy</strong><textarea class="output" rows="14">'+esc(x)+'</textarea>')}
if(slug==='cover-letter-generator'){return setResult('<strong>Draft</strong><textarea class="output" rows="14">Dear Hiring Manager,\\n\\nI am excited to apply for the '+esc(v('role')||'position')+' role at '+esc(v('company')||'your company')+'. My background includes '+esc(v('experience')||'relevant experience and skills')+', and I would welcome the opportunity to contribute to your team.\\n\\nI have focused on delivering clear results, collaborating effectively and improving processes. I would be glad to discuss how my experience aligns with this role.\\n\\nThank you for your consideration.\\n\\nSincerely,\\n[Your Name]</textarea>')}
if(slug==='cover-letter-checker'){const x=v('letter'),w=words(x).length;return setResult('<strong>'+fmt(w)+' words</strong><ul><li>'+(w<=450?'✓ Reasonable length':'○ Consider trimming')+'</li><li>'+(/company|team|role|position/i.test(x)?'✓ Job-specific language detected':'○ Add company/role-specific details')+'</li><li>'+(/[0-9%$]/.test(x)?'✓ Evidence detected':'○ Add concrete results')+'</li></ul>')}
if(slug==='interview-question-generator'){const q=v('role')||'target role',technical=/technical/i.test(v('type'));return setResult(list('Practice questions',technical?['Walk me through a recent technical problem you solved.','How would you debug a production issue?','What trade-offs would you consider?','How do you test your work?','Explain a technical decision simply.']:['Tell me about a challenging situation and what you did.','Why are you interested in this '+esc(q)+' role?','Describe a measurable achievement.','Tell me about a disagreement and how you handled it.','What would your first 90 days look like?']))}
if(slug==='star-method-builder'){return setResult('<strong>STAR outline</strong><textarea class="output" rows="14">Situation: Set the context for '+esc(v('question'))+'.\\n\\nTask: What were you responsible for?\\n\\nAction: What specific steps did you personally take?\\n\\nResult: What changed? Add a number, percentage, time saved, revenue, quality or other evidence.\\n\\nNotes: '+esc(v('story'))+'</textarea>')}
if(slug==='interview-answer-practice'){const x=v('answer'),w=words(x).length;return setResult('<strong>Practice review</strong><ul><li>'+(w>=50?'✓ Enough detail':'○ Add more detail')+'</li><li>'+(/[0-9%$]/.test(x)?'✓ Quantified evidence':'○ Add a measurable result')+'</li><li>'+(/I\\b|my\\b/i.test(x)?'✓ Personal ownership':'○ Clarify what you personally did')+'</li></ul>')}
if(slug==='interview-scorecard'){const avg=['prep','research','stories','questions'].reduce((s,id)=>s+n(id),0)/4;return setResult('<strong>'+fmt(avg*10)+'/100 preparation score</strong><p>Average rating: '+fmt(avg)+'/10.</p>')}
if(slug==='questions-to-ask-interviewer'){const r=v('role')||'this role';return setResult(list('Questions to ask',['What would success look like in the first 90 days in '+esc(r)+'?','What are the most important priorities right now?','How is performance measured?','How does the team collaborate?','What are the next steps?']))}
if(slug==='linkedin-headline-generator'){const r=v('role')||'Professional',s=v('skills')||'Strategy • Execution • Results',z=v('value')||'solve problems and deliver measurable results';return setResult(list('Headline options',[esc(r)+' | '+esc(s),esc(r)+' helping teams '+esc(z),esc(r)+' | '+esc(s)+' | Focused on '+esc(z)]))}
if(slug==='professional-bio-generator'){return setResult('<strong>Short bio</strong><textarea class="output" rows="8">'+esc(v('name')||'Your Name')+' is a '+esc(v('role')||'professional')+' with experience in '+esc(v('experience')||'their field')+'. They focus on practical problem-solving, collaboration and meaningful results.</textarea>')}
if(slug==='career-goal-planner'){return setResult('<strong>30 / 60 / 90 day plan</strong><ul><li><b>Days 1–30:</b> Define '+esc(v('goal'))+', audit skills and identify 3 priority gaps.</li><li><b>Days 31–60:</b> Build evidence through a project, course, portfolio item or targeted applications.</li><li><b>Days 61–90:</b> Measure progress and take the next concrete step toward '+esc(v('date')||'your target date')+'.</li></ul>')}
if(slug==='skills-gap-checker'){const c=uniq(v('current').split(/[,\\n]/)),t=uniq(v('target').split(/[,\\n]/)),g=t.filter(x=>x&&!c.includes(x));return setResult('<strong>'+g.length+' target skills to review</strong><p>'+g.map(esc).join(' · ')+'</p>')}
if(slug==='achievement-statement-generator'){const w=v('work'),r=v('resultText');return setResult(list('Achievement statements',['Improved '+esc(w)+(r?' by '+esc(r):' while improving execution'), 'Delivered '+esc(w)+(r?' resulting in '+esc(r):' with measurable improvement'), 'Streamlined '+esc(w)+(r?' to achieve '+esc(r):' and strengthened the process')]))}
if(slug==='job-application-tracker'){let arr=JSON.parse(localStorage.getItem('career-applications')||'[]');arr.unshift({company:v('company'),role:v('role'),stage:v('stage'),date:v('date'),notes:v('notes')});arr=arr.slice(0,30);localStorage.setItem('career-applications',JSON.stringify(arr));return renderTracker(arr)}
}catch(e){setResult('<strong>Please check the fields.</strong><p>Enter valid information and try again.</p>')}
});
document.addEventListener('click',e=>{if(e.target.id==='clearTracker'){localStorage.removeItem('career-applications');setResult('<strong>Tracker cleared.</strong>') }});
})();